server:
  port: 8081
  servlet:
    context-path: /atrs
spring:
  rabbitmq:
    host: localhost
    virtual-host: /
    port: 5672
    username: admin
    password: 123456
#    connection-timeout: 2000
  mail:
    host: smtp.qq.com
    username: 2927697242@qq.com
    password: nltlcygbednxdgea
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: atrs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/air_ticket_reservation_system?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    host: 8.140.17.235
#    host: 192.168.80.128
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 350MB
mybatis-plus:
  type-aliases-package: com.atrs.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.atrs: debug


